# Generated by Django 4.0.4 on 2022-05-30 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_number', models.CharField(max_length=200)),
                ('amounts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('bank_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_bank_froms', to='bank.bank')),
                ('bank_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_bank_tos', to='bank.bank')),
            ],
        ),
        migrations.AddField(
            model_name='bank',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.customer'),
        ),
    ]
