# Generated by Django 4.0.4 on 2022-05-30 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='bank_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories_bank_from', to='bank.bank'),
        ),
        migrations.AlterField(
            model_name='history',
            name='bank_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories_bank_to', to='bank.bank'),
        ),
    ]
