# Generated by Django 4.0.4 on 2022-06-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_history_bank_from_alter_history_bank_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='amounts',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='history',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
